//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Boleta
    {
        public int Id { get; set; }
        public Nullable<int> Nu_caso { get; set; }
        public Nullable<bool> Motivo1 { get; set; }
        public Nullable<bool> Motivo2 { get; set; }
        public Nullable<bool> Motivo3 { get; set; }
        public Nullable<bool> Motivo4 { get; set; }
        public Nullable<bool> Motivo5 { get; set; }
        public Nullable<bool> Motivo6 { get; set; }
        public Nullable<bool> Motivo7 { get; set; }
        public string Motivo8 { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
    
        public virtual t_Revision t_Revision { get; set; }
    }
}
