//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Institucion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Institucion()
        {
            this.t_Revision = new HashSet<t_Revision>();
        }
    
        public int Codigo { get; set; }
        public int Circuito { get; set; }
        public int Tipo { get; set; }
        public string Nombre { get; set; }
        public string Cedula_Juridica { get; set; }
        public string Cuenta_Danea { get; set; }
        public string Cuenta_Ley { get; set; }
        public string Contador { get; set; }
        public bool Estado { get; set; }
    
        public virtual t_Direccion_Regional t_Direccion_Regional { get; set; }
        public virtual t_Persona t_Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Revision> t_Revision { get; set; }
        public virtual t_Tipo_Institucion t_Tipo_Institucion { get; set; }
    }
}
