//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewEntregaCasos
    {
        public string Consecutivo { get; set; }
        public int Codigo { get; set; }
        public int Circuito { get; set; }
        public string Institucion { get; set; }
        public string Asignado { get; set; }
        public System.DateTime FechaAsignada { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public string Observacion { get; set; }
        public string Mensajero { get; set; }
        public int Cheque { get; set; }
        public Nullable<int> Transferencia { get; set; }
    }
}
