//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewContadores
    {
        public string Cedula { get; set; }
        public int TipoIdentificacion { get; set; }
        public string Carnet { get; set; }
        public string NombreCompleto { get; set; }
        public string Correo { get; set; }
    }
}
