//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewBoleta
    {
        public int Id { get; set; }
        public int Codigo { get; set; }
        public string Consecutivo { get; set; }
        public int Circuito { get; set; }
        public string Nombre { get; set; }
        public string Cedula_Juridica { get; set; }
        public bool Motivo1 { get; set; }
        public bool Motivo2 { get; set; }
        public bool Motivo3 { get; set; }
        public bool Motivo4 { get; set; }
        public bool Motivo5 { get; set; }
        public bool Motivo6 { get; set; }
        public bool Motivo7 { get; set; }
        public string Motivo8 { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public string Nombre_Completo { get; set; }
        public Nullable<int> numeroActa { get; set; }
        public Nullable<int> numeroFolio { get; set; }
        public Nullable<System.DateTime> fechaActa { get; set; }
    }
}
