//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewJuntas
    {
        public int Codigo { get; set; }
        public int Circuito { get; set; }
        public string NombreTipo { get; set; }
        public string Nombre { get; set; }
        public string CedulaJuridica { get; set; }
        public string DiaRuta { get; set; }
        public string CuentaLey { get; set; }
        public string Responsable { get; set; }
        public string Contacto { get; set; }
        public string Contador { get; set; }
        public bool Estado { get; set; }
    }
}
